baseURL: "https://norbertfucsko.github.io/"
title: Norbert Fucsko blog
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Norbert Fucsko blog
  description: "Software & Deep Learning Engineer."
  keywords: [Blog, Portfolio, PaperMod]
  author: Norbert Fucsko
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false
  hideFooter: true

  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "images/favicon.ico"
    favicon16x16: "images/favicon.ico"
    favicon32x32: "images/favicon.ico"

  label:
    text: "Norbert Fucsko"
    icon: /images/artificial-intelligence.png
    darkIcon: /images/artificial-intelligence-dark.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Norbert Fucsko blog
    subtitle: "Software & Deep Learning Engineer."
    imageUrl: "images/profile_pic.jpg"
    imageWidth: 240
    imageHeight: 240
    imageTitle: profile image
    buttons:
      - name: About
        url: /about/
      - name: Posts
        url: /posts/

  # home-info mode
  homeInfoParams:
    # enabled: true
    Title: "Norbert Fucsko blog"
    Content: Software & Deep Learning Engineer.

  socialIcons:
    - name: linkedin
      url: "https://www.linkedin.com/in/norbertfucsko/"
    - name: github
      url: "https://github.com/fucskonorbi"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 10
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 20
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai